apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ha-platform
data:
  postgresql.conf: |
    listen_addresses = '*'
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on

  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    all             all             10.244.0.0/16           trust
    host    replication     all             10.244.0.0/16           trust
